var school=require('./index.js');
school.add([
    {
        teacherName:'Sakura',
        students:[
            'student-01',
            'student-02',
            'student-03'
        ]
    },
    {
        teacherName:'Sakura-02',
        students:[
            'student-11',
            'student-12',
            'student-13'
        ]
    }
]);
